name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./raytracer
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./raytracer
    - name: Test
      run: dotnet raytracer --no-build --verbosity normal
      working-directory: ./raytracer/raytracer/bin/Debug/net6.0
